[phases.setup]
providers = ["python"]

[phases.install]
cmds = ["pip install -r server/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd server && uvicorn main:app --host 0.0.0.0 --port $PORT"